name: Automatic pull request review
on: [pull_request]
#permissions: read-all
# permissions:
#   contents: write
#   pull-requests: write
jobs:
  automate-pullrequest-review:
    runs-on: ubuntu-latest
    steps:
      - name: Approve pull request
        if: github.actor == 'laurentsimon' || github.actor == 'lolodroid9'
        uses: andrewmusgrave/automatic-pull-request-review@0.0.5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          event: APPROVE
          body: 'Thank you laurentimon'
#       - name: Approve pull request
#         if: github.actor == 'laurentsimon'
#         uses: andrewmusgrave/automatic-pull-request-review@0.0.5
#         with:
#           repo-token: ${{ secrets.GITHUB_TOKEN }}
#           event: APPROVE
#           body: 'Thank you 2 laurentimon'
      - uses: pascalgn/automerge-action@v0.15.5
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

#      - uses: reitermarkus/automerge@v2
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
    
