name: Automatic pull request review
on: [pull_request_target]
#permissions: read-all
permissions:
  contents: write
  pull-requests: write
jobs:
  automate-pullrequest-review:
    runs-on: ubuntu-latest
    steps:
      - name: Approve pull request
        if: github.actor == 'laurentsimon' || github.actor == 'lolodroid9'
        uses: andrewmusgrave/automatic-pull-request-review@0.0.5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          event: APPROVE
          body: 'Thank you laurentimon'
#       - name: Approve pull request
#         if: github.actor == 'laurentsimon'
#         uses: andrewmusgrave/automatic-pull-request-review@0.0.5
#         with:
#           repo-token: ${{ secrets.GITHUB_TOKEN }}
#           event: APPROVE
#           body: 'Thank you 2 laurentimon'
      - uses: pascalgn/automerge-action@v0.15.5
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

#      - uses: reitermarkus/automerge@v2
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
    
# test with remote fork
# pull_request: fail with remotee fork
#               succeeds always for local branch, unless 2 LGTM needed. BP settings dont matter it seems
# pull_request_target:
# bypass allowed: success
# bypass not allowed: success
# codeowners set: fail to merge (bypass settings does not matter)
