name: builder id

on:
  workflow_dispatch:

permissions: read-all

env:
  THIS_FILE: e2e.go.push.main.default.slsa3.yml
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  checkout:
    name: checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
      - run: |
          set -euo pipefail
          bash test.sh
