name: goreleaser

on:
  workflow_dispatch:
  push:
    tags:
      - "*" # triggers only if push new tag version, like `0.8.4` or else

permissions:
  contents: read

jobs:
  goreleaser:
    permissions:
      contents: write  # for goreleaser/goreleaser-action to create a GitHub release
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v2.3.4
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923 # v2.2.0
        with:
          go-version: 1.17
      -
        name: Run GoReleaser
        id: build
        uses: goreleaser/goreleaser-action@b953231f81b8dfd023c58e0854a721e35037f28b # v2.5.0
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: print
        env:
          ARTIFACTS: "${{ steps.build.outputs.artifacts }}"
          METADATA: "${{ steps.build.outputs.metadata }}"
        run: |
          echo "artifacts: $(echo $ARTIFACTS | base64 -w0)"
          echo "metadata: $(echo $METADATA | base64 -w0)"
          
          checksum_file=$(echo "$ARTIFACTS" | jq -r '.[] | select (.type=="Checksum") | .path')
          cat $checksum_file
