name: Label PR

on:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    if: ${{ github.event.label.name == 'label-test' }}
    runs-on: ubuntu-latest

    steps:
    - name: Debug
      run: echo "GITHUB_SHA: $$GITHUB_SHA"
