name: Run unit tests
on:
  pull_request:
    branches: [main]

permissions: {}

jobs:
  model-signing-unit-tests:
    name: Run unit tests for signing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
      with:
        python-version: 3.11
        cache: pip
        cache-dependency-path: |
          .github/workflows/scripts/requirements.txt
    - name: Install dependencies
      run: |
        set -euo pipefail
        python -m venv venv
        source venv/bin/activate
        python -m pip install --require-hashes -r .github/workflows/scripts/requirements.txt
        tree venv/
        echo "$PATH"
    - name: Run unit tests
      run: |
        set -euo pipefail
        pytest .