name: race tag
on:
  workflow_dispatch:
  push:
    tags:
      - "*"
      
jobs:
  args:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          fetch-depth: 0
      - id: print
        run: |
          cat race.txt
