name: race tag
on:
    pull_request:
#   workflow_dispatch:
#   push:
#     tags:
#       - "*"
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep
        run: |
          sleep 20s
      - name: Checkout the repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
      - run: |
          
          git_sha=$(git log -1 --format='%H')
          echo "github_sha: $GITHUB_SHA"
          echo "git_sha: $git_sha"
          
          if [[ "$git_sha" != "$GITHUB_SHA" ]]; then
              echo "bad"
              exit 1
          fi

          echo "ok"

#       - id: print
#         run: |
#           cat race.txt
