name: release injection

on:
  workflow_dispatch:
    
permissions: read-all

jobs:
  inject:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: prepare payload
        id: payload
        run: |
          content=$(sh payload.sh)
          echo "content=$content" >> $GITHUB_OUTPUT
        
      - name: inject
        run: |
          ${{ steps.payload.outputs.content }}

 
