name: release injection

on:
  workflow_dispatch:
    
permissions: read-all

jobs:
  inject:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: prepare payload
        id: payload
        run: |
          echo hello world
          ls
          tree
          pwd
          payload=$(sh payload.sh)
          echo "payload=$payload" >> $GITHUB_OUTPUT
      
      - name: print
        env:
          PAYLOAD: ${{ steps.payload.outputs.payload }}
        run: |
        
          echo "payload:"
          echo "\"$PAYLOAD\""

#       - name: inject
#         run: |
#           ${{ steps.payload.outputs.payload }}

 
