name: Reusable 1
on:
  workflow_call:
  
permissions:
  contents: read

jobs:
  args:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: oidc
        run: |
        
          jwt=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=testaudience")
          value=$(echo "$jwt" | base64 -w0)
          echo "JWT reusable 1:"
          echo "$value"

  call2:
    permissions:
      id-token: write
      contents: read
    uses: laurentsimon/slsa-on-github-test/.github/workflows/reusable2.yml@main
