name: Reusable 1
on:
  workflow_call:
  
permissions: read-all

jobs:
  args:
    permissions:
      token-id: write
    runs-on: ubuntu-latest
    steps:
      - name: oidc
        run: |
        
          JWT=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=testaudience")
          echo "JWT reusable 1:"
          echo "$JWT"

  call2:
    permissions:
      token-id: write
    uses: laurentsimon/slsa-on-github-test/.github/workflows/reusable2.yml@main
