name: Reusable 2
on:
  workflow_call:
  
permissions:
  contents: read

jobs:
  args:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: oidc
        run: |
        
          jwt=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=testaudience")
          value=$(echo "$jwt" | jq -r '.value' | cut -f2 -d '.' | base64 -d | jq)
          echo "JWT reusable 2:"
          echo "$value"
