name: SLSA generic generator
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: new release version
        required: true
        default: (for example, 0.1.0)
      some_bool:
        description: other
        required: false
        default: true
      some_integer:
        description: other
        required: false
        default: "123"
  push:
    tags:
      - "*"
#   release:
#     types: [created]

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      digests: ${{ steps.hash.outputs.digests }}

    steps:
      # ========================================================
      #
      # Step 1: Build your artifacts.
      #
      # ========================================================      
      - name: Build artifacts
        run: |
            # These are some amazing artifacts.
            echo "artifact1" > artifact1
            echo "artifact2" > artifact2
      # ========================================================
      #
      # Step 2: Add a step to generate the provenance subjects
      #         as shown below. Update the sha256 sum arguments
      #         to include all binaries that you generate
      #         provenance for.
      #
      # ========================================================
      - name: Generate subject
        id: hash
        run: |
          set -euo pipefail
          echo "::set-output name=digests::$(sha256sum artifact1 artifact2 | base64 -w0)"
  provenance:
    needs: [build]
    permissions:
      actions: read   # To read the workflow path.
      id-token: write # To sign the provenance.
      contents: write # To add assets to a release.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.2.0
    with:
      base64-subjects: "${{ needs.build.outputs.digests }}"
      upload-assets: true # Optional: Upload to a new release
