name: test grep

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  checkout:
    name: verify grep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      - run: bash ./grep.sh

