name: test self

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  checkout:
    name: test self
    runs-on: ubuntu-latest
    steps:
      - uses: laurentsimon/hello-github-actions/action-a@v1.0.0
