name: Upload folder

on: 
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create folder
        env:
          FOLDER_NAME: "my-folder"
          FOLDER_INSIDE_NAME: "inside"
          FOLDER_EMPTY_NAME: "empty"
        run: |
          set -euo pipefail
          
          # TODO: empt
          mkdir -p "${FOLDER_NAME}/${FOLDER_INSIDE_NAME}"
          mkdir -p "${FOLDER_NAME}/${FOLDER_EMPTY_NAME}"
          
          echo file1 > "${FOLDER_NAME}"/file1
          echo file2 > "${FOLDER_NAME}"/file2
          echo file3 > "${FOLDER_NAME}"/${FOLDER_INSIDE_NAME}/file3
          echo file4 > "${FOLDER_NAME}"/${FOLDER_INSIDE_NAME}/file4
          
          tree "${FOLDER_NAME}

      - name: Upload
        id: upload
        uses: laurentsimon/slsa-on-github-test/.github/actions/secure-upload-folder@main
        with:
          name: "the-name"
          path: my-folder
      
      - name: debug
        env:
          SHA256: ${{ steps.upload.outputs.sha256 }}
        run: |
          echo "SHA256: $SHA256"
          mkdir output-folder

      - name: Download
        id: download
        uses: laurentsimon/slsa-on-github-test/.github/actions/secure-download-folder@main
        with:
          name: "the-name"
          path: output-folder
          sha256: ${{ steps.upload.outputs.sha256 }}
      
      - name: debug
        run: |
          tree output-folder/
