name: workflow start

on:
  pull_request:
  workflow_dispatch:
    inputs:
      return_value:
        default: "0"
        required: false
        type: string

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Save event name
        env:
          EVENT_NAME: ${{ github.event_name }}
        run: |
          mkdir -p ./event
          echo $EVENT_NAME > ./event/event_name
      - uses: actions/upload-artifact@v3
        with:
          name: event_name
          path: event/
      - run: exit $return_value
