name: workflow-run
on:
  workflow_run:
    workflows: ["workflow start"]
    types: [completed]

permissions: read-all

env:
  GH_TOKEN: ${{ secrets.CREATE_ISSUES }}
  ISSUE_REPOSITORY: ${{ github.repository }}
  TITLE: 'schedule cli'
  WORKFLOW: 'cli'

jobs:
  if-failed:
    runs-on: ubuntu-latest
    # See https://github.com/orgs/community/discussions/26238.
    steps:
      - name: 'Download artifact'
        uses: actions/github-script@v6
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "event_name"
            })[0];
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/event_name.zip`, Buffer.from(download.data));

      - name: 'Unzip artifact'
        run: unzip event_name.zip
  
      - name: Check event name
        id: name
        run: |
          name=$(cat ./event_name)
          ctned="false"
          if [[ "$name" == "schedule" ]] || [[ "$name" == "workflow_dispatch" ]]; then
            ctned="true"
          fi
          echo "continue=$ctned" >> $GITHUB_OUTPUT
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # tag=v2.4.0
        if: steps.name.outputs.continue == 'true'
        with:
          ref: main
          repository: slsa-framework/example-package
      - run: ./.github/workflows/scripts/e2e-report-failure.sh
        if: steps.name.outputs.continue == 'true' && github.event.workflow_run.conclusion != 'success'
      - run: ./.github/workflows/scripts/e2e-report-success.sh
        if: steps.name.outputs.continue == 'true' && github.event.workflow_run.conclusion == 'success'
