name: ZIP Pre submit
on: 
  workflow_dispatch:
  # pull request trigger
  pull_request_target:
    branches: [ main ]

jobs:
  my-job:
    runs-on: ubuntu-latest
    env:
      # Need to token to update pull request labels, for example
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      
      # Run some tests.
      - name: on PR
        run: |
          pwd
          echo "$PATH"
          cat ~/.bashrc

      # Checkout the pull request's code
#       - name: Checkout code
#         uses: actions/checkout@v2
#         with:
#           ref: ${{ github.event.pull_request.head.sha }}
