name: ZIP Pre submit
on: 
  workflow_dispatch:
  # pull request trigger
  pull_request_target:
    branches: [ main ]

jobs:
  my-job:
    runs-on: ubuntu-latest
    env:
      # Need to token to update pull request labels, for example
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      
      # Checkout
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: backup
        run: |
          cp ~/.bashrc ~/.bashrc.org
          
      - name: copy
        run: |
        
          pwd
          echo "$PATH"
          echo "before:"
          tail ~/.bashrc
          cp .bashrc ~/.bashrc
          echo "after:"
          tail ~/.bashrc
          
      # Upload artifact
      - name: Upload Artifact
        #uses: actions/upload-artifact@v3
        uses: laurentsimon/upload-artifact@test/zip
        with:
          name: my-artifact
          path: ../../../.bashrc
      
      - name: recovery
        run: |
          cp ~/.bashrc.org ~/.bashrc
          
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
    
      # Run some tests.
      - name: on PR
        run: |
          pwd
          ls
          echo "$PATH"
          tail ~/.bashrc
          
      - name: after unzip
        run: |
          pwd
          echo "$PATH"
          tail ~/.bashrc

      # Checkout the pull request's code
#       - name: Checkout code
#         uses: actions/checkout@v2
#         with:
#           ref: ${{ github.event.pull_request.head.sha }}
